#!/bin/sh

__check_if_port_installed() {
    local port="$1"

    if ! pkg info ${port} > /dev/null 2>&1; then
        echo "${port} not installed"
        #return 0
    else
        echo "${port} installed"
        #return 1
    fi
}

__check_if_key_in_file() {
    local key="$1"
    local file="$2"

    if [ -f ${file} ]
    then
        if grep -Fxq "${key}" ${file}
        then
            return 0
        else
            return 1
        fi
    fi

    return 0
}

__check_if_key_in_file CCACHE_DIR /etc/make.conf
if [ $? -eq 0 ]
then
    echo "CCACHE_DIR is present"
else
    echo "CCACHE_DIR is NOT present"
    echo "CCACHE_DIR is NOT present" >> ./test_result
fi

__check_if_key_in_file WITH_CCACHE_BUILD /etc/make.conf
if [ $? -eq 0 ]
then
    echo "WITH_CCACHE_BUILD is present"
else
    echo "WITH_CCACHE_BUILD is NOT present"
    echo "WITH_CCACHE_BUILD is NOT present" >> ./test_result
fi

__check_if_port_installed git
__check_if_port_installed firefox