#!/bin/sh

. $(dirname "$0")/scripts/utils

__is_user_allowed_to_update() {
  group=$(id -G -n $USER | grep -o "installer")
  if [ "${group}" == "installer" ]; then
    echo true
  else
    echo false
  fi
}

__is_installed() {
  __log_info "Checking if $1 is installed..."
  if ! [ -x "$(command -v $1)" ]; then
    __log_error "Error: $1 is not installed." >&2
    exit 1
  fi
}

__check_docker_requirements() {
  __log_info "Checking docker Requirements..."
  # Check if docker and vagrant are installed
  __is_installed vagrant
  __is_installed docker-machine
  __is_installed docker
  __is_installed docker-compose
}

__xsession_setup() {
  __log_info "Copying .xinitrc under ${HOME}"
  __backup_file ${HOME}/.xinitrc
  cp ./dotfiles/xinitrc ${HOME}/.xinitrc

  __log_info "Copying .Xdefaults under ${HOME}"
  __backup_file ${HOME}/.Xdefaults
  cp ./dotfiles/Xdefaults ${HOME}/.Xdefaults
}

__shell_setup() {
  __log_info "Copying .tcshrc under ${HOME}"
  __backup_file ${HOME}/.tcshrc
  cp ./dotfiles/tcshrc ${HOME}/.tcshrc
}

__conky_setup() {
  __log_info "Copying Conky Configuration Files under ${HOME}..."
  __backup_file ${HOME}/.conkyrc
  cp ./dotfiles/conkyrc ${HOME}/.conkyrc
}

__gtk_theme_setup() {
  __log_info "Copying gtk2/gtk3 Configuration Files under ${HOME}..."
  __backup_file ${HOME}/.gtkrc-2.0
  cp ./dotfiles/gtkrc-2.0 ${HOME}/.gtkrc-2.0

  __log_info "Copying settings.ini Configuration Files under ${HOME}/.config/gtk-3.0..."
  mkdir -p ${HOME}/.i3-config/gtk-3.0
  __backup_file ${HOME}/.i3-config/gtk-3.0/settings.ini
  cp ./dotfiles/settings.ini ${HOME}/.i3-config/gtk-3.0/settings.ini
}

__i3gaps_setup() {
  mkdir -p ~/.i3-config/i3/wallpapers/
  __backup_file ${HOME}/.i3-config/i3/i3-config
  cp ./i3gaps/i3-config ${HOME}/.i3-config/i3

  cp ./wallpapers/* ${HOME}/.i3-config/i3/wallpapers/
  cp -r ./i3gaps-scripts ${HOME}/.local/scripts/
}

__docker_setup() {
  if [ "${is_docker_enabled}" == "false" ]; then
    return
  fi

  __check_docker_requirements
  mkdir -p ${HOME}/.local/scripts

  __log_info "Installing docker configuration..."
  __wait_for_seconds 5
  mkdir -p ${HOME}/Development/Vagrant/dockervm
  cp ./i3gaps/Vagrantfile ${HOME}/Development/Vagrant/dockervm/Vagrantfile

  __log_info "Configuring docker..."
  __wait_for_seconds 5
  mkdir -p ${HOME}/Development/Vagrant/dockervm
  cp ./openbox/Vagrantfile ${HOME}/Development/Vagrant/dockervm/Vagrantfile

  # Do not use this in production. This is just fine for local development
  docker-machine create \
    --driver generic \
    --generic-ip-address 127.0.0.1 \
    --generic-ssh-port 2222 \
    --generic-ssh-user docker \
    --generic-ssh-key ~/.vagrant.d/insecure_private_key \
    boot2docker-vbox
}

__setup_user_update_script() {
  if [ "${user_can_update}" == "true" ]; then
    __log_info "Installing Update Scripts under ${HOME}/.local/scripts..."
    __wait_for_seconds 5

    fetch --no-verify-hostname --no-verify-peer -o /tmp/update_script.tar.gz https://api.github.com/repos/HiMyNameIsIlNano/update_script/tarball/master
    mkdir /tmp/update_script_${timestamp}
    tar xvzf /tmp/update_script.tar.gz --strip=1 -C /tmp/update_script_${timestamp}

    cd /tmp/update_script_${timestamp}
    sh install
    __log_info "Cleaning Temporary Files..."
    cd
    rm -rf /tmp/update_script_${timestamp}
  else
    __log_warn "Skipping Copying Update Scripts under ${HOME}/.local/scripts as ${USER} is not member of the group installer..."
  fi
}

__setup_vim() {
  __is_installed curl
  __is_installed vim

  cp dotfiles/vimrc ~/.vimrc
  mkdir -p ~/.vim/undodir
  mkdir -p ~/.vim/plugged

  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  vim +PluginInstall +qall
}

work_dir=.
config_file=${work_dir}/i3gaps_installer.config

while [ "$1" != "" ]; do
  case $1 in
  -c | --i3-config)
    shift
    config_file=$1
    echo ${config_file}
    ;;
  -h | --help)
    usage
    exit
    ;;
  *)
    usage
    exit 1
    ;;
  esac
  shift
done

# Variable Declaration
user_can_update=$(__is_user_allowed_to_update)
is_docker_enabled=$(__read_property enable_docker)
is_setup_vpn_enabled=$(__read_property setup_vpn)
geany_tag_base_url=http://download.geany.org/contrib/tags
timestamp=$(date +%s)

__log_info "Start configuring Openbox Desktop Look & Feel..."

__pcmanfm_setup

__xsession_setup

__shell_setup

__i3gaps_setup

__task_bar_setup

__conky_setup

__gtk_theme_setup

__docker_setup

__setup_vim

__setup_user_update_script

cat $timestamp > ~/.config/openbox/init.finished

exit 0
