#!/bin/sh

. $(dirname "$0")/scripts/utils

work_dir=.
config_file=${work_dir}/freebsd_configurer.config

while [ "$1" != "" ]; do
    case $1 in
	    -c | --config )		    shift
                                config_file=$1
                                echo ${config_file}
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

value='An Additional Message'
__log_error 'This is an error'
__log_warn 'This is a warning'
__log_info 'This is an info'
__log_info "This is an info: ${value}"

exit 0

sh ./scripts/create_users

sh ./scripts/download_kernel

sh ./scripts/install_software

# Configure sudoers file /boot/loader.conf and /etc/rc.conf
sh ./scripts/configure_startup_daemons

# Configure Groups and Users
sh ./scripts/configure_groups

echo "### Restart computer now... ###"
__wait_for_input
shutdown -r now

exit 0
