#!/bin/sh

# Begin Functions
__wait_for_input(){
	printf 'press [ENTER] to continue...'
	read dummy
}
# End Functions

work_dir=.
config_file=${work_dir}/freebsd_configurer.config

while [ "$1" != "" ]; do
    case $1 in
	    -c | --config )		    shift
                                config_file=$1
                                echo ${config_file}
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

sh ./scripts/create_users

sh ./scripts/download_kernel

sh ./scripts/install_software

# Configure sudoers file /boot/loader.conf and /etc/rc.conf
sh ./scripts/configure_startup_daemons

# Configure Groups and Users
sh ./scripts/configure_groups

echo "### Restart computer now... ###"
__wait_for_input
shutdown -r now

exit 0
