#!/bin/sh

. $(dirname "$0")/scripts/utils

work_dir=.
config_file=${work_dir}/freebsd_installer.config

while [ "$1" != "" ]; do
  case $1 in
  -c | --config)
    shift
    config_file=$1
    echo ${config_file}
    ;;
  -h | --help)
    usage
    exit
    ;;
  *)
    usage
    exit 1
    ;;
  esac
  shift
done

sh ./scripts/create_users

sh ./scripts/download_kernel

sh ./scripts/install_base_pkgs

# Configure sudoers file /boot/loader.conf and /etc/rc.conf
sh ./scripts/configure_startup_daemons

# Configure Groups and Users
sh ./scripts/configure_groups

sh ./scripts/download_window_manager_installer

__log_warn "### Restart computer now... ###"
__wait_for_input
shutdown -r now

exit 0
