#!/bin/sh

# Begin Functions
__init_ports() {
	local max_size="$1"
	
	echo "Initializing ports..."
	__wait_for_seconds 5
	
	portsnap fetch
	portsnap extract	
	
	cd /usr/ports/devel/ccache BATCH=yes
	make install clean
	
	echo "WRKDIRPREFIX=/ram" >> /etc/make.conf
	echo "CCACHE_DIR=/var/cache/ccache" >> /etc/make.conf
	echo "WITH_CCACHE_BUILD=yes" >> /etc/make.conf
	
	mkdir /ram
	echo 'none /ram tmpfs rw,size=2147483648 0 0' >> /etc/fstab
	mount /ram
	
	echo "max_size = ${max_size}" >> ~/.ccache/ccache.conf
	echo "cache_dir = /var/cache/ccache" >> ~/.ccache/ccache.conf
}
	
__is_installed(){
	if ! [ -x "$(command -v $1)" ]; then
	    echo "Error: $1 is not installed." >&2
        return 1
    else
        return 0
	fi
}

__check_requirements(){
	# Check if git is installed
	__is_installed git
	if [ $? -eq 1 ]
	then
        printf "Do you want to add install git? [Y/n]: "
		read dummy
		if [ "${dummy}" == "Y" ]
		then
		    __install_ports git
		else
		    exit 1
		fi
	fi
}

__wait_for_seconds(){
	local seconds="$@"
	echo "waiting ${seconds} seconds before continuing..."
	sleep ${seconds}
}

__read_property(){
	input="$@"
	temp=`cat ${config_file} | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
	echo ${temp##*|}
}

__get_port_dir() {
	local port_name="$1"
	local port_dir=$(whereis ${port_name})
	echo ${port_dir##*|}
} 

__install_ports(){
	local ports_to_install="$@"
	# The list of ports must be comma separated with no empty space
	for port in $(echo ${ports_to_install} | sed "s/,/ /g")
	do
		local port_dir=get_port_dir $port
		cd ${port_dir} && make install clean BATCH=yes
	done	
}

__post_config_java8(){
	__is_installed_java 001008

	if [ $? -eq 0 ] ; then
		echo "fdesc	/dev/fd		fdescfs		rw	0	0" >> /etc/fstab
		echo "proc	/proc		procfs		rw	0	0" >> /etc/fstab
	else
		echo "Java Version is not 1.8"
	fi
}
# End Functions

while [ "$1" != "" ]; do
    case $1 in
	-c | --config )		shift
                                config_file=$1
                                echo ${config_file}
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

# Check if GIT is installed
__check_requirements
 
# Variable Declaration
base_ports=$(__read_property base_ports)
desktop_ports=$(__read_property desktop_ports)
dev_ports=$(__read_property dev_ports)
office_ports=$(__read_property office_ports)
# TODO: read value from property file
ccache_size=5G

work_dir=.
config_file=${work_dir}/post_install.config

# Init Ports tree and Ramdisk for faster compilation
__init_ports ${ccache_size}

echo "Initializing Ports Tree..."
echo "Installing ports..."
__wait_for_seconds 5
__install_ports ${base_ports}

echo "Installing desktop ports..."
__wait_for_seconds 5
__install_ports ${desktop_ports}

echo "Installing office ports..."
__wait_for_seconds 5
__install_ports ${office_ports}

echo "Installing development ports..."
__wait_for_seconds 5
__install_ports ${dev_ports}

# Finalize Java8 Configuration
__post_config_java8

exit 0
