#!/bin/sh

# Begin Functions
__read_property(){
    input="$@"
    temp=`cat ${config_file} | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
    echo ${temp##*|}
}

__check_if_pkg_installed() {
    local pkg="$1"

    if ! pkg info ${pkg} > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

__check_if_port_installed() {
    local port="$1"

    if ! pkg info ${port} > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

__check_requirements() {
    __check_if_port_installed wget
    __check_if_port_installed git
    __check_if_port_installed yarn
    __check_if_port_installed python2.7
}
# End Functions

__check_requirements
fetch --no-verify-hostname --no-verify-peer -o /tmp/electron-v2.0.1-freebsd-x64.tar.gz https://api.github.com/repos/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/tarball/master
mkdir /tmp/electron-v2.0.1-freebsd-x64
tar xvzf /tmp/electron-v2.0.1-freebsd-x64.tar.gz --strip=1 -C /tmp/electron-v2.0.1-freebsd-x64
cp ./patch/vscode_buildv1.26.0.sh.diff /tmp/electron-v2.0.1-freebsd-x64/vscode/
cd /tmp/electron-v2.0.1-freebsd-x64/vscode
patch < vscode_buildv1.26.0.sh.diff
sh vscode_buildv1.26.0.sh