#!/bin/sh

# Begin Functions
__read_property(){
    input="$@"
    temp=`cat ${config_file} | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
    echo ${temp##*|}
}

__check_if_pkg_installed() {
    local pkg="$1"

    if ! pkg info ${pkg} > /dev/null 2>&1; then
        echo "${pkg} not installed on the system"
        return 0
    else
        return 1
    fi
}

__check_requirements() {
    local return_code=0
    __check_if_pkg_installed wget
    if [ $? -eq 0 ]
    then
        return_code=1
    fi

    __check_if_pkg_installed git
    if [ $? -eq 0 ]
    then
        return_code=1
    fi

    __check_if_pkg_installed yarn
    if [ $? -eq 0 ]
    then
        return_code=1
    fi

    __check_if_pkg_installed python27
    if [ $? -eq 0 ]
    then
        return_code=1
    fi

    return ${return_code}
}
# End Functions

__check_requirements
if [ $? -eq 1 ]
then
    exit 1
fi

if [ -f /tmp/electron-v2.0.1-freebsd-x64.tar.gz ]
then
    rm /tmp/electron-v2.0.1-freebsd-x64.tar.gz
fi
fetch --no-verify-hostname --no-verify-peer -o /tmp/electron-v2.0.1-freebsd-x64.tar.gz https://api.github.com/repos/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/tarball/master

if [ -d /tmp/electron-v2.0.1-freebsd-x64 ]
then
    rm -r /tmp/electron-v2.0.1-freebsd-x64
fi
mkdir /tmp/electron-v2.0.1-freebsd-x64

tar xvzf /tmp/electron-v2.0.1-freebsd-x64.tar.gz --strip=1 -C /tmp/electron-v2.0.1-freebsd-x64
cp ./patch/vscode_buildv1.26.0.sh.diff /tmp/electron-v2.0.1-freebsd-x64/vscode/
cd /tmp/electron-v2.0.1-freebsd-x64/vscode
patch < vscode_buildv1.26.0.sh.diff
sh vscode_buildv1.26.0.sh
exit 0