#!/bin/sh

# Begin Functions
__check_if_pkg_installed() {
    local pkg="$1"

    if ! pkg info ${pkg} > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

__check_requirements() {
    local pkgs_to_install=speech-dispatcher,snappy,libxslt
    __install_pkgs ${pkgs_to_install}
}

__install_pkgs(){
	pkgs_to_install="$@"

	# The list of ports must be comma separated with no empty space
	for pkg in $(echo $pkgs_to_install | sed "s/,/ /g")
	do
	    __check_if_pkg_installed ${pkg}
	    if [ $? -eq 0 ]
	    then
		    pkg install -y ${pkg}
        else
            echo "${pkg} already installed on the system"
	    fi
	done
}

# End Functions

__check_requirements
wget https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/releases/download/vscode_v1.26.0/VSCode-freebsd-x64-1.26.0.tar.xz
mv ./VSCode-freebsd-x64-1.26.0.tar.xz /tmp/
mkdir -p /tmp/VSCode-freebsd-x64-1.26.0
tar -xf /tmp/VSCode-freebsd-x64-1.26.0.tar.xz --strip=1 -C /tmp/VSCode-freebsd-x64-1.26.0
sh /tmp/VSCode-freebsd-x64-1.26.0/code-oss