#!/bin/sh

# Begin Functions
__read_property(){
	input="$@"
	temp=`cat $config_file | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
	echo ${temp##*|}
}

__check_if_pkg_installed() {
    local pkg="$1"

    if ! pkg info ${pkg} > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

__get_port_dir() {
	local port_name="$1"
	local port_dir=$(whereis -q ${port_name})
	echo ${port_dir##*|}
}

__check_if_port_installed() {
    local port="$1"

    if ! pkg info ${port} > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

__install_ports(){
	local ports_to_install="$@"

	# The list of ports must be comma separated with no empty space
	for port in $(echo ${ports_to_install} | sed "s/,/ /g")
	do
	    __check_if_port_installed ${port}
	    if [ $? -eq 0 ]
	    then
	    	local port_dir=$(__get_port_dir $port)
	    	cd ${port_dir} && make install clean BATCH=yes
        else
          value='An Additional Message'
          __log_warn "${port} already installed on the system"
	    fi
	done
}

__install_pkgs(){
	pkgs_to_install="$@"

	# The list of ports must be comma separated with no empty space
	for pkg in $(echo $pkgs_to_install | sed "s/,/ /g")
	do
	    __check_if_pkg_installed ${pkg}
	    if [ $? -eq 0 ]
	    then
		    pkg install -y ${pkg}
        else
          __log_warn "${pkg} already installed on the system"
	    fi
	done
}
# End Functions

work_dir=..
config_file=${work_dir}/freebsd_configurer.config

while [ "$1" != "" ]; do
    case $1 in
	    -c | --config )		    shift
                                config_file=$1
                                echo ${config_file}
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

# Variable Declaration
port_system=$(__read_property port_system)
dependencies_to_install=speech-dispatcher,snappy,libxslt,wget
version=1.26.0
artifact_url=https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/releases/download/vscode_v${version}/VSCode-freebsd-x64-${version}.tar.xz

if [ ${port_system} == "PKG" ]
then
    __install_pkgs ${dependencies_to_install}
fi

if [ ${port_system} == "PORT" ]
then
    __install_ports ${dependencies_to_install}
fi

wget  ${artifact_url} -O /tmp/VSCode-freebsd-x64-${version}.tar.xz
mkdir -p /usr/local/share/VSCode-freebsd-x64-${version}
tar -xf /tmp/VSCode-freebsd-x64-${version}.tar.xz --strip=1 -C /usr/local/share/VSCode-freebsd-x64-${version}

if [ -f /usr/local/bin/vscode-${version} ]
then
    rm /usr/local/bin/vscode-${version}
fi
ln -s /usr/local/share/VSCode-freebsd-x64-${version}/code-oss /usr/local/bin/vscode-${version}

exit 0