#!/bin/sh

. $(dirname "$0")/utils

__add_user_to_group(){
	local group="$@"
	local user
	local dummy=Y

	while
		__log_warn "Which user would you like to add to group ${group}?: "
		read user

		__log_info "Adding user ${user} to group ${group}..."
		pw group mod ${group} -m ${user}

		__log_warn "Do you want to add another user to group ${group}? [Y/n]: "
		read dummy
		[ "${dummy}" == "Y" ]            # test the limit of the loop.
	do :;  done
}

work_dir=.
config_file=${work_dir}/i3gaps_installer.config

while [ "$1" != "" ]; do
    case $1 in
	    -c | --i3-config )		    shift
                                config_file=$1
                                echo ${config_file}
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

# Variable Declaration
port_system=$(__read_property port_system)

__log_warn "### IMPORTANT NOTE ###"
__log_warn "Make sure that all the users are part of the 'video' group, otherwise it won't be possible for the user(s) to start a graphic session"
__add_user_to_group video
clear

__log_warn "Make sure that all the users are part of the 'operator' group, otherwise it won't be possible for the user(s) to automount USB sticks"
__add_user_to_group operator
clear

__log_warn "Add members to the 'vboxusers' group, otherwise it won't be possible for anyone to launch virtualbox"
__add_user_to_group vboxusers
clear

__log_warn "Add members to the 'restarter' group, otherwise it won't be possible for anyone to restart or power down the computer"
__add_user_to_group restarter
clear

if [ ${port_system} == "PKG" ]
then
  __log_warn "Add members to the 'installer' group, otherwise it won't be possible for anyone to install programs apart from the root user"
  __add_user_to_group installer
  clear
fi

if [ ${port_system} == "PORT" ]
then
	__log_warn "Add members to the 'wheel' group, otherwise it won't be possible for anyone to install programs apart from the root user"
  __add_user_to_group wheel
  clear
fi

__log_warn "Make sure that all the users are part of the 'vpnstarter' group, otherwise it won't be possible for the user(s) to launch openvpn"
__add_user_to_group vpnstarter
clear

exit 0