#!/bin/sh

. $(dirname "$0")/utils

__add_user_to_group() {
  local group="$@"
  local user
  local dummy=Y

  while [ "${dummy}" == "Y" ]; do
    __log_warn "Do you want to add a user to group ${group}? [Y/n]: "
    read dummy

    if [ "${dummy}" == "n" ]; then
      break
    fi

   __log_warn "Which user would you like to add to group ${group}?: "
    read user

    __log_info "Adding user ${user} to group ${group}..."
    pw group mod ${group} -m ${user}
  done
}

work_dir=.
config_file=${work_dir}/freebsd_installer.config

while [ "$1" != "" ]; do
  case $1 in
  -c | --config)
    shift
    config_file=$1
    echo ${config_file}
    ;;
  -h | --help)
    usage
    exit
    ;;
  *)
    usage
    exit 1
    ;;
  esac
  shift
done

# Variable Declaration
port_system=$(__read_property port_system)
configure_groups=$(__read_property configure_groups)
is_virtualbox_guest=$(__read_property is_virtualbox_guest)

clear

if [ "${configure_groups}" == "false" ]; then
  exit 0
fi

if [ "${is_virtualbox_guest}" == "true" ]; then
  virtualbox_group=', 'vboxusers''
fi

if [ ${port_system} == "PKG" ]; then
  installer_group=', 'installer''
fi

if [ ${port_system} == "PORT" ]; then
  installer_group=', 'wheel''
fi

__log_warn "### IMPORTANT NOTE ###"
__log_warn "Make sure that all the users are part of the 'video', 'operator', 'restart' ${virtualbox_group} ${installer_group} groups"
__wait_for_input

bsdconfig usermgmt

exit 0
