#!/bin/sh

. $(dirname "$0")/scripts/utils

work_dir=.
config_file=${work_dir}/freebsd_configurer.config

while [ "$1" != "" ]; do
    case $1 in
	    -c | --config )		    shift
                                config_file=$1
                                echo ${config_file}
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

download_kernel=$(__read_property download_kernel)
timestamp=$(date +%s)

if [ "${download_kernel}" == "true" ]
then
    __wait_for_seconds 5
	echo "Downloading kernel source..."
	if [ -d /usr/src ]
	then
	    # backup folder
	    mv /usr/src /usr/src_${timestamp}
	fi

	fetch ftp://ftp.freebsd.org/pub/`uname -s`/releases/`uname -m`/`uname -r`/src.txz
    tar -C / -xvzf src.txz
fi

