#!/bin/sh

__show_menu() {
  NORMAL=$(echo "\033[m")
  MENU=$(echo "\033[36m")   #Blue
  NUMBER=$(echo "\033[33m") #yellow
  FGRED=$(echo "\033[41m")
  RED_TEXT=$(echo "\033[31m")
  ENTER_LINE=$(echo "\033[33m")
  echo -e "${MENU}*********************************************${NORMAL}"
  echo -e "${MENU}**${NUMBER} 1)${MENU} Install i3gaps ${NORMAL}"
  echo -e "${MENU}**${NUMBER} 2)${MENU} Install openbox ${NORMAL}"
  echo -e "${MENU}*********************************************${NORMAL}"
  echo -e "${ENTER_LINE}Select ${RED_TEXT}any of the choices. ${NORMAL}"
}

function __i3gaps_install() {
  fetch --no-verify-hostname --no-verify-peer -o /tmp/i3gaps_freebsd.tar.gz https://api.github.com/repos/HiMyNameIsIlNano/my_freebsd/tarball/i3gaps-desktop
  mkdir -p /tmp/i3gaps_freebsd
  tar xvzf /tmp/i3gaps_freebsd.tar.gz --strip=1 -C /tmp/i3gaps_freebsd
  cd /tmp/i3gaps_freebsd

  sh i3_installer
}

function __openbox_install() {
  fetch --no-verify-hostname --no-verify-peer -o /tmp/openbox_freebsd.tar.gz https://api.github.com/repos/HiMyNameIsIlNano/my_freebsd/tarball/openbox-desktop
  mkdir -p /tmp/openbox_freebsd
  tar xvzf /tmp/openbox_freebsd.tar.gz --strip=1 -C /tmp/openbox_freebsd
  cd /tmp/openbox_freebsd

  sh openbox_installer
}

__show_menu
read wm_idx

case $wm in
  1) __i3gaps_install ;;
  2) __openbox_install ;;
  *)
    echo "No entry matching by that number!"
    __show_menu
    ;;
esac
