#!/bin/sh

. $(dirname "$0")/utils

__check_if_pkg_installed() {
  local pkg="$1"

  if ! pkg info ${pkg} >/dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}

__install_pkgs() {
  pkgs_to_install="$@"

  # The list of ports must be comma separated with no empty space
  for pkg in $(echo $pkgs_to_install | sed "s/,/ /g"); do
    __check_if_pkg_installed ${pkg}
    if [ $? -eq 0 ]; then
      pkg install -y ${pkg}
    else
      __log_warn "${pkg} already installed on the system"
    fi
  done
}

__is_command_installed() {
  if ! [ -x "$(command -v $1)" ]; then
    return 0
  else
    return 1
  fi
}
# End Functions

work_dir=.
config_file=${work_dir}/freebsd_installer.config

while [ "$1" != "" ]; do
  case $1 in
  -c | --config)
    shift
    config_file=$1
    ;;
  -h | --help)
    usage
    exit
    ;;
  *)
    usage
    exit 1
    ;;
  esac
  shift
done

# Variable Declaration
base_pkgs=$(__read_property base_ports)
timestamp=$(date +%s)

__log_info "Initializing PKG System..."
__log_info "Updating package DB..."
pkg update

__log_info "Installing base packages..."
__wait_for_seconds 5
__install_pkgs ${base_pkgs}

if [ "${is_virtualbox_guest}" == "true" ]; then
  __log_info "Optimizing Virtualbox Guest..."
  __wait_for_seconds 5

  __install_pkgs virtualbox-ose-additions

  echo 'vboxguest_enable="YES"' >>/etc/rc.conf
  #cp ./virtualbox/xorg/xorg.conf /etc/X11/
fi

exit 0
