#!/bin/sh

# Utility Functions
__read_property(){
	input="$@"
	temp=`cat $config_file | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
	echo ${temp##*|}
}

__wait_for_input(){
	printf 'press [ENTER] to continue...'
	read dummy
}

__wait_for_seconds(){
	local seconds="$@"
	echo "waiting ${seconds} seconds before continuing..."
	sleep ${seconds}
}

__log_error(){
	local text="$@"
	RED='\033[0;31m'
	WHITE='\033[0;37m'
  NC='\033[0m'
  printf "${RED}[ERROR] ${WHITE}${text}${NC}\n"
}

__log_warn(){
	local text="$@"
	YELLOW='\033[0;32m'
	WHITE='\033[0;37m'
  NC='\033[0m'
  printf "${YELLOW}[INFO] ${WHITE}${text}${NC}\n"
}

__log_info(){
	local text="$@"
	GREEN='\033[0;33m'
	WHITE='\033[0;37m'
  NC='\033[0m'
  printf "${GREEN}[WARN] ${WHITE}${text}${NC}\n"
}