#!/bin/sh
sleep 2 &

# Make sure the init is run once
if [ ! -f ~/.config/openbox/init.finished ]; then
  xterm -title "Initialize the desktop environment" -e "/tmp/my_freebsd/first_usage_init"
fi

(sleep 2 && tint2) &
(sleep 2 && conky) &
feh --bg-scale $HOME/.config/openbox/wallpapers/red-background.jpg &

urxvtd -q -f -o &
#(sleep 2 && setxkbmap xx) &
(sleep 2 && compton -b) &